// apps/ng-nx-exec/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'storybook-props-mismatch-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'ng-nx-exec';
}

<h1>Angular app using Nx storybook executor</h1>
<p>Title: {{ title }}</p>
<p>Rating: {{ rating }}</p>
<p>Flag: {{ flag ? 'true' : 'false' }}</p>

// apps/re-native/src/app/app.tsx
export interface AppProps {
  title: string;
  rating: number;
  flag: boolean;
}

export function App(props: AppProps) {
  return (
    <div>
      <h1>React app using native storybook</h1>
      <p>Title: {props.title}</p>
      <p>Rating: {props.rating}</p>
      <p>Flag: {props.flag ? 'true' : 'false'}</p>
    </div>
  );
}

export default App;
